---
- name: "Customizing sh3llvik@pwnbox"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
  