- name: "Installing more tools..."
  apt:
    name:
      # Note: Uncomment packages as needed
      # - exploitdb  # Exploit database CLI tools
      - sublist3r  # Subdomain enumeration tool
      # - ffuf       # Fuzzing tool
      - httprobe    # HTTP probing tool
    state: present
