---
- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - terminator
      - synapse
      - kitty
      - neovim
    state: latest
  become: true
  become_method: sudo
