- name: "Download Kerbrute binary"
  become: true
  get_url:
    url: https://github.com/ropnop/kerbrute/releases/download/v1.0.0/kerbrute-linux-amd64
    dest: /usr/sbin/kerbrute
    mode: '0755'

- name: "Ensure Kerbrute is executable"
  become: true
  file:
    path: /usr/sbin/kerbrute
    mode: '0755'
