- name: "Install Golang (if not installed)"
  become: true
  apt:
    name: golang
    state: present

- name: "Clone the Kerbrute repository"
  become: true  # Use root permissions to clone to /opt
  git:
    repo: 'https://github.com/ropnop/kerbrute.git'
    dest: '/opt/kerbrute'  # Destination directory to clone the repo
    update: yes

- name: "Build Kerbrute binary"
  become: true
  shell: |
    cd /opt/kerbrute
    go build -o /usr/sbin/kerbrute
  args:
    creates: /usr/sbin/kerbrute  # This prevents re-building if the file already exists

- name: "Ensure Kerbrute is executable"
  become: true
  file:
    path: /usr/sbin/kerbrute
    mode: '0755'
