---
- name: "Install python tools in virtualenv"
  become: yes  # Elevate privileges
  apt:
    name: python3-venv
    state: present

- name: "Create a virtual environment"
  become: yes  # Elevate privileges
  shell: python3 -m venv /opt/venv

- name: "Ensure pip is installed in the virtual environment"
  become: yes  # Elevate privileges
  shell: /opt/venv/bin/python -m ensurepip --upgrade

- name: "Upgrade pip to latest"
  become: yes  # Elevate privileges
  shell: /opt/venv/bin/python -m pip install --upgrade pip

- name: "Install tools using pip"
  become: yes  # Elevate privileges
  pip:
    name: "{{ item.name }}"
    extra_args: "{{ item.url | default(omit) }}"
    virtualenv: /opt/venv
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'git+https://github.com/Porchetta-Industries/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
